services:
  # Frontend Service
  - type: web
    name: iks-rag-ui
    runtime: node
    rootDir: iks-rag-ui
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://your-backend-url.onrender.com
    autoDeploy: true

  # Backend Service
  - type: web
    name: iks-rag-api
    runtime: python
    rootDir: iks-rag-pipelines
    buildCommand: pip install -r api/requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: QDRANT_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    autoDeploy: true 