services:
  - type: web
    name: iks-rag-ui
    runtime: node
    rootDir: iks-rag-ui
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://your-backend-url.onrender.com
    autoDeploy: true 